# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
#  config.vm.synced_folder "libs/", "/vlibs", type: "rsync"
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.hostname = "smb"
  config.vm.network "public_network"
  config.vm.provision "shell", inline: "rm -rf *"
  config.vm.provision "file", source: "../../smb.zip", destination: "smb.zip"
  config.vm.provision "file", source: "../../localdev-config.json", destination: "localdev-config.json"
  config.vm.provision "file", source: "startsmb.sh", destination: "startsmb.sh"
  config.vm.provision "shell", path: "bootstrap.sh"
end
