# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
#  config.vm.synced_folder "libs/", "/vlibs", type: "rsync"
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.hostname = "smb"
  config.vm.network "public_network"
  # config.vm.provision "shell", inline: "rm -rf *"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.synced_folder "../..", "/home/vagrant/rtc-smb", type: "virtualbox"
  config.vm.hostname = "vagrantdev.local.net"
  config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 4
  end
end
