name: C++ Static code analysis

on: [push, pull_request]

jobs:
  cppcheck:
    name: run-cppcheck
    runs-on: ubuntu-latest
    container:
      image: neszt/cppcheck-docker:2.9
    steps:
      - uses: actions/checkout@v3
      - run: cppcheck --version
      - run: cppcheck --error-exitcode=1 --std=c++17 --language=c++ -j$(getconf _NPROCESSORS_ONLN) -I . -i test/ -i external/ -i build/ --suppressions-list=.cppcheck-suppressions --inline-suppr .
      - run: cppcheck --error-exitcode=1 --std=c++17 --language=c++ -j$(getconf _NPROCESSORS_ONLN) -I . -I test/include --suppressions-list=.cppcheck-suppressions --inline-suppr ./test
