name: C++ Static code analysis

on: [push, pull_request]

jobs:
  cppcheck:
    name: run-cppcheck
    runs-on: ubuntu-latest
    container:
      image: neszt/cppcheck-docker:latest
    steps:
    - uses: actions/checkout@v3
    - run: cppcheck --version
    - run: cppcheck --error-exitcode=1 --std=c++14 --language=c++ --suppress=objectIndex:transport/ice/Stun.cpp -i test/ -I . .
    - run: cppcheck --error-exitcode=1 --std=c++14 --language=c++ -I . -I test/include ./test
