name: PR Unit Test

on: [pull_request]

jobs:
  pr-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: aws-linux
            build.type: Release
          # - os: el7
          #   build.type: Release
          - os: el8
            build.type: Release
          - os: ubuntu-focal-deb
            build.type: Release
          - os: ubuntu-focal
            build.type: Release
          - os: el8
            build.type: LCheck
          - os: el8
            build.type: TCheck
          - os: el8
            build.type: DCheck
          - os: el8
            build.type: LCov
    container:
      image: ghcr.io/finos/symphonymediabridge/buildsmb-${{ matrix.os }}:latest
      #credentials:
      #  username: ${{ github.actor }}
      #  password: ${{ secrets.GITHUB_TOKEN }}  # Auth for private image if needed
    steps:
      - uses: actions/checkout@v3
      - name: Mark workspace as safe
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Build
        run: docker/${{ matrix.os }}/buildscript.sh ${{ matrix.build.type }}
      - name: Run Tests
        run: docker/${{ matrix.os }}/runtests.sh
