name: PR Unit Test

on: [pull_request]

jobs:
  pr-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: aws-linux
            build.type: Release
          # - os: el7
          #   build.type: Release
          - os: el8
            build.type: Release
          - os: ubuntu-focal-deb
            build.type: Release
          - os: ubuntu-focal
            build.type: Release
          - os: el8
            build.type: LCheck
          - os: el8
            build.type: TCheck
          - os: el8
            build.type: DCheck
          - os: el8
            build.type: LCov
    container:
      image: ghcr.io/finos/symphonymediabridge/${{ matrix.os }}:latest
    steps:
      - uses: actions/checkout@v3
      - run: docker/${{ matrix.os }}/buildscript.sh ${{ matrix.build.type }}"
      - run: "docker/${{ matrix.os }}/runtests.sh"
