name: PR Unit Test

on: [pull_request]

# make GHA actions use node16 which still works with aws-linux
# See https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
# Unclear how long this will work though
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  pr-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: aws-linux
            build:
              type: Release
          # - os: el7
          #   build.type: Release
          - os: el8
            build:
              type: Release
          - os: ubuntu-focal-deb
            build:
              type: Release
          - os: ubuntu-focal
            build:
              type: Release
          - os: el8
            build:
              type: LCheck
          - os: el8
            build:
              type: TCheck
          - os: el8
            build:
              type: DCheck
          - os: el8
            build:
              type: LCov
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref }}-${{ matrix.os }}-${{ matrix.build.type }}
      cancel-in-progress: true
    container:
      image: ghcr.io/finos/symphonymediabridge/buildsmb-${{ matrix.os }}:latest
    steps:
      - uses: actions/checkout@v3
      - name: Mark workspace as safe
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Build
        run: docker/${{ matrix.os }}/buildscript.sh ${{ matrix.build.type }}
      - name: Run Tests
        run: docker/${{ matrix.os }}/runtests.sh
      - name: Upload Unit test logs
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-logs-${{ matrix.os }}-${{ matrix.build.type }}
          retention-days: 14
          path: ${{ matrix.os }}/smb/smb_unit_test*.log
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.build.type }}
          retention-days: 14
          path: ${{ matrix.os }}/smb/test-results/test-results*.xml
      - name: Annotate test results
        uses: dorny/test-reporter@v1
        if: failure() # Only run this step if there is a failure
        with:
          name: Unit Tests
          path: ${{ matrix.os }}/smb/test-results/test-results*.xml
          reporter: junit
